version: '3.6'

services:

  server:
    build:
      context: ./server
      dockerfile: apache.Dockerfile
    ports:
      - 80:80
    volumes:
      - type: bind
        source: /web
        target: /var/www/html/

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
    links:
      - server

  db:
    build: ./database
    volumes:
      - /storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "dewy"
      MYSQL_PASSWORD: "dewy"
      MYSQL_DATABASE: "drupal8"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    restart: always
    ports:
    - 8080:80
    links:
      - db
      - server